### ISSUE TITLE
how to use on node.js site

### ISSUE THREAD

**Issue by espoal** [yyjhao/markmon#13]
Hi! 

Very nice app!

I'm trying to build an open source latex editor, and I stumbled upon your project. Is it possibile to run this package in a node (meteor) site? 

I got the impression this package will automatically start his own node server, thus not being usable on an already running server. But I'm also very noob, so I could be totally wrong :P

**Comment by yyjhao** [comment]
Yes I think that will be possible. You may want to take a look at the code in `/frontend`. All the diff algorithm is done in front end JavaScript.
