### ISSUE TITLE
Changing the HTML rendering

### ISSUE THREAD

**Issue by mtbirdsall** [yyjhao/markmon#17]
I am new to pandoc, but I am using markmon for rendering markdown.  I like to get the preview in HTML with this tool, but can I edit the parsing so I get a cleaner look.  My code chucks offset with "`" don't highlight a different color and the font's look dated.  
- [ ] Is this a pandoc issue and if so would you recommend editing pandoc or finding a new parser?
  - [ ] If I should find a new parser, which do you recommend for material, flat design?

**Comment by yyjhao** [comment]
You can use a custom stylesheet with `--stylesheet` to style the whole page including the fonts for code blocks. See https://github.com/yyjhao/markmon#how-to-use
