### ISSUE TITLE
Mathjax render problem

### ISSUE THREAD

**Issue by molikto** [yyjhao/markmon#7]
![bug](https://cloud.githubusercontent.com/assets/1373829/3090306/8129a1b8-e58a-11e3-94ca-455d32af85ce.jpg)

All mathjax is rendered twice sometimes. I am not familiar about your algorithm, though I am really excited about this project and want to make contribution, it will be approciated if you can inspect this bug.

**Comment by yyjhao** [comment]
Can you give some minimum markdown code that reproduce the problem? That will be very helpful.

**Comment by molikto** [comment]
I cannot reproduce it with small size file. It might just be that [my markdown file](https://github.com/molikto/hakyll/blob/master/mathematics.md) is too big. The diff algorithm takes 500ms, and I am restricting the refresh time interval to 1s in Sublime Text, or it will get very busy sending the text to node.js

**Comment by yyjhao** [comment]
Your file is way to large. Just running pandoc on my computer takes around 3s. It is not really realistic to fix bugs for this kind of files because the performance gain won't really matter. I suggest you split it into smaller files or don't use the preview at all.

**Comment by danielgeier** [comment]
Happens with my (small) markdown files, too.

**Comment by danielgeier** [comment]
For example a file consisting simply of $1 + 1 = 2$. Try rendering that, now change the 2 to a 3 and save.

![image](https://cloud.githubusercontent.com/assets/566219/13054011/a635751e-d407-11e5-97f3-f2f2217604a0.png)
