### ISSUE TITLE
Missing images (not showing up)

### ISSUE THREAD

**Issue by edouard-lopez** [yyjhao/markmon#9]
I'm using relative path to images. However none is showing up with the default configuration. For intance:
## Markdown

``` markdown
# My awesome project

![dataviz preview](./preview.png)

blabla bla.
```

**Comment by edouard-lopez** [comment]
### Solution

Configuring the `projectdir` property in `…/Packages/User/sublime-text-markmon.sublime-settings` to your readme directory solve this:

``` json
    "projectdir": "/path/to/readme-directory"
```

**Comment by takashyx** [comment]
Does anybody have an idea to automatically set projectdir like that?

**Comment by nolanbconaway** [comment]
Ideally, this would be configurable on a project-by-project basis, ostensibly by setting a `projectdir`item in the project settings file.
